In [1]:
#saving & loading from/into the file using pickle and joblib

In [2]:
import pandas as pd
from sklearn import linear_model

In [8]:
df=pd.read_csv("homeprices.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [17]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [23]:
reg.predict([[5000,3,10]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([819484.67272357])

In [24]:
import pickle

In [32]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [33]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [34]:
mp.predict([[5000,3,10]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([819484.67272357])

In [38]:
import joblib

In [39]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [40]:
mj = joblib.load('model_joblib')

In [41]:
mj.predict([[5000,3,10]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([819484.67272357])